config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  get "about" => "homes#about"
  resources :users, only:[:show, :index, :edit, :update]
  resources :books, only:[:show, :index, :edit, :update, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  
  def get_image
    (image.attached?) ? image: "no_image.png"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books

  def get_profile_image
    (profile_image.attached?) ? profile_image: "no_image.png"

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
 
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

 
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action:authenticate_user!, except:[:index, :show]

  def index
    @books = Book.all
    
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to user_path(current_user)
    end

  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to user_path(current_user)
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      redirect_to user_path(current_user)
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body, :image)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except:[:index, :show]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user)
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :caption, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="home-content">
  <h2 class="page-title">book編集</h2>
  <%= form_with model: @book do |f| %>
    <p>タイトル</p>
    <%= f.text_field :title %><br>
    <p>感想</p>
    <%= f.text_area :body %>
    <%= f.file_field :image, accept:"image/*" %>
  <%= f.submit "変更を保存" %>
<% end %>
</div>

app/views/books/index.html.erb
<div class="home-content">
  <div class="books-visual">
    <h2 class="page-title">Books</h2>
    <p>
      Books-Life<br>
      貴方のお気に入りの一冊が見つかりますように。
    </p>
  </div>
</div>

<div class="home-content">投稿一覧</div>
<div class="wrapper grid">
  <% @books.each do |book| %>
    <div class="item">
      <%= image_tag book.get_image, size: "300x300" %>
      <p><%= link_to book.title, book_path(book) %></p>
      <p><%= book.body %></p>
    </div>
  <% end %>
</div>

app/views/books/show.html.erb
<div class="home-content">
  <h2 class="pagi-title">book</h2>
  <p>タイトル</p>
  <%= @book.title %>
  <p>感想</p>
  <%= @book.body %>

  <% if @book.user == current_user %>
    <%= link_to "編集する", edit_book_path(@book) %>
    <%= link_to "削除する", book_path(@book), method: :delete %>
  <% end %>
</div>

app/views/homes/about.html.erb
<h1>このサイトについて</h1>
<p>本が好きな人もそうでない人も、ここで一息ついてみませんか？</p>

<div class="big-box">
<div class="box1"></div>
<div class="box2"></div>
<div class="box3"></div>
<div class="box4"></div>
<div class="box5"></div>
<div class="box6"></div>
</div>

app/views/homes/top.html.erb
  <div class="home-content">
    <div class="top-visual">
      <div class="top-visual-content">
        <h2 class="page-title">no-book-no-life</h2>
        <%= link_to "新規会員登録はこちら", new_user_registration_path, class: "button edit-link" %>
        <%= link_to "ログインはこちら", new_user_session_path, class: "edit-link"%>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="home" class="big-bg">
    <header class="page-header wrapper">
      <h1 class="heading">Bookers3!</h1>

      <nav>
        <ul class="main-nav">
          <% if user_signed_in? %>
        <li><%= link_to "マイページ", user_path(current_user), class: "edit-link" %></li>
        <li><%= link_to "Books", books_path, class: "edit-link" %></li>
        <li><%= link_to "Users", users_path, class: "edit-link"%></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "edit-link" %></li>
      <% else %>
        <li><%= link_to "新規登録", new_user_registration_path, class: "edit-link" %></li>
        <li><%= link_to "ログイン", new_user_session_path, class: "edit-link" %></li>
      <% end %>
        </ul>
      </nav>
    </header>
    <%= yield %>
    <footer>
      <p class="home-content">©2023 bookers3</p>
    </footer>

    </div>
  </body>
</html>

app/views/users/edit.html.erb
<h1>会員編集</h1>
<%= form_with model: @user do |f| %>
<p>アイコン画像</p>
<%= f.file_field :profile_image, accept:"image/*" %>
<p>お名前</p>
<%= f.text_field :name %>
<p>自己紹介</p>
<%= f.text_area :caption %>
<%= f.submit "保存する"%>
<% end %>

app/views/users/index.html.erb
<div class="home-content">
  <div class="user-visual">
    <h2 class="page-title">users</h2>
  </div>
</div>

<div class="wrapper">
<% @users.each do |user| %>
  <div class="user-content">
  <%= image_tag user.get_profile_image, size: "50x50" %>
  <%= user.name %>
  <%= user.caption %>
  </div>
<% end %>
</div>

app/views/users/show.html.erb
<h1>会員ページ</h1>
<div class="home-content">
  <div class="user-show-visual">
    <div class="user-show-visual-content">
      <%= image_tag @user.get_profile_image, size: "150x150" %>
      <p><%= @user.name %></p>
      <p><%= @user.caption %></p>
      
      <% if @user == current_user %>
        <%= link_to "編集する", edit_user_path(@user) %>
      <% end %>
    </div>
  </div>

  <% if @user == current_user %>
    <p>投稿する</p>
    <%= form_with model: @book do |f| %>
      <p>タイトル</p>
      <%= f.text_field :title, class: "form-text" %>
      <p>感想</p>
      <%= f.text_area :body, class: "form-area" %>
      <p>画像</p>
      <%= f.file_field :image, accept:"image/*" %>
      <%= f.submit "投稿" %>
    <% end %>
  <% end %>
</div>

<div class="home-content">投稿したもの</div>
<div class="wrapper grid">
  <% @books.each do |book| %>
    <div class="item">
      <%= image_tag book.get_image, size: "300x300" %>
      <p><%= link_to book.title, book_path(book) %></p>
      <p><%= book.body %></p>
      <% if @user == current_user %>
        <p><%= link_to "編集", edit_book_path(book) %></p>
      <% end %>
    </div>
  <% end %>
</div>